<?php
	/* Template Name: Analytics Page Template */
	if (!is_user_logged_in()) {
		//auth_redirect();
		$url = get_site_url() . '/log-in/';
		wp_safe_redirect( $url );
	}
	get_header();
	get_template_part('templates/content', 'inner-header');
	
	global $post;
	$wp_current_user_id = get_current_user_id();
?>

<main id="main" role="main" class="community analytics">
	<style>
		h5 {
			font-size: 16px;
			font-weight: 500;
			margin-bottom: 10px;
		}
		.tags-wrapper {
			text-align: center;
		}
	</style>

	<div class="bookshelf-heading-filter-wrapper flex justify-space-between align-items-center">
		<h3><?php echo get_the_title(); ?></h3>
	</div>
	
	<section>
		<div class="icon-wrapper icon-medium full-width bg-lt-blue">
			<div class="icon-background">
				<?php echo file_get_contents( get_stylesheet_directory() . '/img/friends.svg'); ?>
			</div>
			<h4>By the Numbers</h4>
		</div>
		<div id="tagsList" class="tags-list">
			<h4 class='title'>Number of finished books in each category:</h4>
			<?php
				$all_book_tags = array();
				$book_entries = $wpdb->get_results("SELECT * FROM {$wpdb->prefix}bookworm_books WHERE user_id_shelf = '$wp_current_user_id' AND date_finished IS NOT NULL AND date_finished != '0000-00-00' AND date_finished != '1970-01-01' ORDER BY date_finished DESC");
				foreach ($book_entries as $book_entry) {
					if ($book_entry->tags != NULL && $book_entry->tags != '' && !empty($book_entry->tags)) {
						$book_entry_tags = explode(',', $book_entry->tags);
						//$book_entry_tags = json_decode(stripslashes($book_entry->tags), true);
						$all_book_tags = array_merge($all_book_tags, $book_entry_tags);
					} 
				}
				if (!empty($all_book_tags)) {
					$all_book_tags = array_unique($all_book_tags);
			?>
				<div class="tags-wrapper">
					<ul>
			<?php
					foreach ($all_book_tags as $tagID) {
						$tag = get_tag($tagID);
						$book_count = $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}bookworm_books WHERE user_id_shelf = %d AND date_finished IS NOT NULL AND date_finished != '0000-00-00' AND date_finished != '1970-01-01' AND FIND_IN_SET(%d, tags)", $wp_current_user_id, $tagID));

			?>
					<div class="tag-count-wrapper">
						<li class="tag-entry active <?php echo $tag->slug; ?>" data-id="<?php echo $tag->slug; ?>"><?php echo $tag->name; ?></li>
						<span class="book-count"><?php echo $book_count; ?></span>
					</div>
			<?php
					}
			?>
					</ul>
				</div>
			<?php
				}
			?>
		</div> <!-- close tags-list -->

		<div id="timePeriodsList" class="time-periods-list">
			<h4 class='title'>Number of finished books in each time period:</h4>
			<div class="flex gap-20 text-center">
			<?php
				$date_query_field = 'date_finished';
				$filterClosure = create_year_filter($date_query_field);
				$countCurrentYear = count(array_filter($book_entries, $filterClosure));
				echo "<div><h5>Year-to-Date</h5>
				<div class='text'>" . $countCurrentYear . "</div></div>";

				$filterClosure = create_date_filter($date_query_field, 3);
				$countThreeMonths = count(array_filter($book_entries, $filterClosure));
				echo "<div><h5>Past 3 Months</h5>
				<div class='text'>" . $countThreeMonths . "</div></div>";
				$filterClosure = create_date_filter($date_query_field, 6);
				$countSixMonths = count(array_filter($book_entries, $filterClosure));
				echo "<div><h5>Past 6 Months</h5>
				<div class='text'>" . $countSixMonths . "</div></div>";
				$filterClosure = create_date_filter($date_query_field, 12);
				$countTwelveMonths = count(array_filter($book_entries, $filterClosure));
				echo "<div><h5>Past Year</h5>
				<div class='text'>" . $countTwelveMonths . "</div></div>";
			?>
		</div>
	</section>
	
	<section>
		<div class="icon-wrapper icon-medium full-width bg-lt-blue">
			<div class="icon-background">
				<?php echo file_get_contents( get_stylesheet_directory() . '/img/iconb_recommend.svg'); ?>
			</div>
			<h4>AI Summary of Notes</h4>
		</div>
		<div class="gemini-ai-summary-wrapper">
			<?php 
				// Call Gemini via API in wp-setup.php
				$summary = get_gemini_user_notes_summary($wp_current_user_id);

				echo '<div class="ai-summary"><h4 class="title">Summary of your book notes:</h4>
				<p>' . esc_html($summary) . '</p>
				<p><em>Generated by Google Gemini</em></p>
				</div>';
			?>
		</div>
		
	</section>
	
	<!--
	<section>
		<h2>Book Clubs</h2>
		<p>Coming soon!</p>
	</section>
	-->
	
	<?php // get_template_part('templates/content', 'side-nav'); ?>

</main>
</div> <!-- close wrapper -->

<?php get_template_part('templates/content', 'footer-nav'); ?>

<div id="popup" class="popup-wrapper">
	<div class="popup popup-large">
		<a class="close-button popup-close" href="#"><img src="<?php echo get_stylesheet_directory_uri() . '/img/icon_close.svg'; ?>" alt="Close button" /></a>
		<div id="popupContainer"></div>
		<p><a id="close-popup" href="#" class="popup-link popup-close">Add Another Friend?</a></p>
	</div>
</div>

<div id="popup_remove_friend" class="popup-wrapper">
	<div class="popup popup-large">
		<a class="close-button popup-close" href="#"><img src="<?php echo get_stylesheet_directory_uri() . '/img/icon_close.svg'; ?>" alt="Close button" /></a>
		<h4>Are you sure you want to remove this friend?</h4>
		<p>You will no longer be connected on BookWorm and recommendations from this friend for books that are not on your bookshelf will be removed.</p>
		<p><a id="remove_friend_confirm" href="#" class="popup-link">Remove friend</a></p>
	</div>
</div>

<div class="loading-animation">
	<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><circle cx="4" cy="12" r="3" fill="currentColor"><animate id="svgSpinners3DotsBounce0" attributeName="cy" begin="0;svgSpinners3DotsBounce1.end+0.25s" calcMode="spline" dur="0.6s" keySplines=".33,.66,.66,1;.33,0,.66,.33" values="12;6;12"/></circle><circle cx="12" cy="12" r="3" fill="currentColor"><animate attributeName="cy" begin="svgSpinners3DotsBounce0.begin+0.1s" calcMode="spline" dur="0.6s" keySplines=".33,.66,.66,1;.33,0,.66,.33" values="12;6;12"/></circle><circle cx="20" cy="12" r="3" fill="currentColor"><animate id="svgSpinners3DotsBounce1" attributeName="cy" begin="svgSpinners3DotsBounce0.begin+0.2s" calcMode="spline" dur="0.6s" keySplines=".33,.66,.66,1;.33,0,.66,.33" values="12;6;12"/></circle></svg>
</div>

<script type="text/javascript">
	document.addEventListener('DOMContentLoaded', function () {
		let addFriendForm = document.getElementById('add_friend_form');
		let loadingAnimation = document.querySelector('.loading-animation');
		let popupNextStep = document.querySelector('#popup');
		let popupRemFriend= document.querySelector('#popup_remove_friend');
		let remFriendForm = document.querySelector('#remove_friends_form'); 
		let remove_friend_confirm = document.getElementById('remove_friend_confirm');
		let validationError = document.getElementById('validation_error');

		addFriendForm.addEventListener('submit', function(event) {
			event.preventDefault();
			
			if (document.getElementById('enter_bookworm_code').value !== '') {
				if (validationError.classList.contains('active')) {
					validationError.classList.remove('active');
				}
				loadingAnimation.classList.add('active');
				var formData = new FormData(this);
				
				formData.append("action", "add_friend");
				fetch([bookwormAjax.url], { // use your ajax url
					method: "POST",
					credentials: "same-origin",
					body: formData // put your data into fetch body
				})
					.then((response) => response.text())
					.then((text) => {
						console.log(text);
						let popupContainer = document.getElementById('popupContainer'); 
						popupContainer.innerHTML = text;
					})
					.then((data) => {
					loadingAnimation.classList.remove('active');
					addFriendForm.reset();
					window.scrollTo({top: 0, behavior: 'smooth'});
					popupNextStep.classList.add('active');
					if (data) {
						console.log(data);
					}
					})
					.catch((error) => {
						console.log("[ OPS!! add_friend ]");
						console.error(error);
					});
					
					// Refresh friends list
					formData.append("action", "friends_list");
				fetch([bookwormAjax.url], { // use your ajax url
					method: "POST",
					credentials: "same-origin",
					body: formData // put your data into fetch body
				})
					.then((response) => response.text())
					.then((text) => {
						console.log(text);
						const friendsList = document.getElementById('remove_friends_form'); 
						friendsList.innerHTML = text;
					})
					.then((data) => {
						loadingAnimation.classList.remove('active');
						if (data) {
							console.log(data);
						}
					})
					.catch((error) => {
						console.log("Friends list refresher not working :(");
						console.error(error);
					});
			} else {
				validationError.classList.add('active');
				let yOffset = -200; 
				let element = document.getElementById('enter_bookworm_code');
				let y = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
				window.scrollTo({top: y, behavior: 'smooth'});
			}
		})
		
		// Remove Friends
		let removeButtons = document.querySelectorAll('.remove-button');
		let popup_remove_friend = document.querySelector('#popup_remove_friend');

		removeButtons.forEach((removeButton) => {
			removeButton.addEventListener('click', function(event) {
				event.preventDefault();
	
				window.scrollTo({top: 0, behavior: 'smooth'});
				popup_remove_friend.classList.add('active');
				
				let remFriendId = this.dataset.friendid;
				let remove_friend_id = document.getElementById('remove_friend_id');
				console.log(remFriendId);
				remove_friend_id.value = remFriendId;
	
				remove_friend_confirm.addEventListener('click', function(event) {
					event.preventDefault();
					loadingAnimation.classList.add('active');
	
					formData = new FormData(remFriendForm);
					formData.append("action", "remove_friend");
	
					fetch([bookwormAjax.url], { // use your ajax url
				    method: "POST",
				    credentials: "same-origin",
				    body: formData // put your data into fetch body
				  })
				    .then((response) => response.text())
					.then((text) => {
						console.log(text);
					})
				    .then((data) => {
				      if (data) {
				        console.log(data);
				      }
					  loadingAnimation.classList.remove('active');
					  window.location.href = "/community/";
				    })
				    .catch((error) => {
				      console.log("I never see these errors. Anyway, removing friend didn't work.");
				      console.error(error);
				    });
				});
			});
		});
		
		let popupClose = document.querySelectorAll('.popup-close');
		let popupTriggers = document.querySelectorAll('.popup-trigger');
		
		popupTriggers.forEach((popupTrigger) => {
			popupTrigger.addEventListener('click', function(e) {
				e.preventDefault();
				
				let popupId = popupTrigger.getAttribute('href');
				
				console.log('click ' + popupId);
				document.querySelector(popupId).classList.add('active');
			})
		})

		popupClose.forEach((popupCloser) => {
			popupCloser.addEventListener('click', function(e){
				e.preventDefault();
				/*popupCloser.classList.remove('active');*/
				e.target.closest('.popup-wrapper').classList.remove('active');
			});
		})
	}, false);
</script>

<?php get_footer(); ?>